// Unified Patient Data Service
// Collects and persists patient data from Chatbot and Symptom Checker

export interface PatientHistoryEntry {
  id: string;
  userId: string;
  source: 'chatbot' | 'symptom-checker';
  timestamp: Date;
  data: {
    text?: string;
    symptoms?: string[];
    imageAnalysis?: {
      symptoms: string[];
      confidence: number;
      recommendations: string[];
    };
    vitalSigns?: {
      bloodPressure?: string;
      heartRate?: number;
      temperature?: number;
      oxygenLevel?: number;
    };
    emotionAnalysis?: {
      emotion: string;
      confidence: number;
      tone: string;
      urgency: 'low' | 'medium' | 'high' | 'critical';
      voiceQuality: string[];
    };
  };
}

export interface ConversationMessage {
  id: string;
  text: string;
  sender: 'bot' | 'user';
  time: string;
  timestamp: Date;
}

export interface PatientDataStore {
  userId: string;
  conversationHistory: ConversationMessage[];
  symptomCheckerHistory: PatientHistoryEntry[];
  lastUpdated: Date;
}

export interface AutoGeneratedReport {
  reportId: string;
  userId: string;
  patientName: string;
  generatedAt: Date;
  symptoms: string[];
  medicalHistory: string;
  conversationSummary: string;
  totalInteractions: number;
  dateRange: { start: Date; end: Date };
}

class PatientDataService {
  private storageKey = 'mediguide_patient_data';
  private reportsKey = 'mediguide_auto_reports';

  // Get patient data store for a specific user
  private getDataStore(userId: string): PatientDataStore {
    const stored = localStorage.getItem(`${this.storageKey}_${userId}`);
    if (stored) {
      const data = JSON.parse(stored);
      return {
        ...data,
        conversationHistory: data.conversationHistory.map((msg: any) => ({
          ...msg,
          timestamp: new Date(msg.timestamp)
        })),
        symptomCheckerHistory: data.symptomCheckerHistory.map((entry: any) => ({
          ...entry,
          timestamp: new Date(entry.timestamp)
        })),
        lastUpdated: new Date(data.lastUpdated)
      };
    }
    return {
      userId,
      conversationHistory: [],
      symptomCheckerHistory: [],
      lastUpdated: new Date()
    };
  }

  // Save data store
  private saveDataStore(data: PatientDataStore): void {
    localStorage.setItem(`${this.storageKey}_${data.userId}`, JSON.stringify(data));
  }

  // Add chatbot conversation message
  addChatbotMessage(userId: string, message: ConversationMessage): void {
    const store = this.getDataStore(userId);
    store.conversationHistory.push(message);
    store.lastUpdated = new Date();
    this.saveDataStore(store);
  }

  // Add symptom checker entry
  addSymptomCheckerEntry(userId: string, entry: Omit<PatientHistoryEntry, 'id' | 'userId'>): void {
    const store = this.getDataStore(userId);
    const newEntry: PatientHistoryEntry = {
      id: `symptom-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      userId,
      ...entry
    };
    store.symptomCheckerHistory.push(newEntry);
    store.lastUpdated = new Date();
    this.saveDataStore(store);
  }

  // Get all patient history (chronological)
  getPatientHistory(userId: string): PatientHistoryEntry[] {
    const store = this.getDataStore(userId);
    
    // Convert conversation history to history entries
    const chatEntries: PatientHistoryEntry[] = store.conversationHistory
      .filter(msg => msg.sender === 'user')
      .map(msg => ({
        id: msg.id,
        userId,
        source: 'chatbot' as const,
        timestamp: msg.timestamp,
        data: {
          text: msg.text
        }
      }));

    // Combine and sort by timestamp
    const allEntries = [...chatEntries, ...store.symptomCheckerHistory];
    return allEntries.sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime());
  }

  // Get conversation history
  getConversationHistory(userId: string): ConversationMessage[] {
    const store = this.getDataStore(userId);
    return store.conversationHistory;
  }

  // Get symptom checker history
  getSymptomCheckerHistory(userId: string): PatientHistoryEntry[] {
    const store = this.getDataStore(userId);
    return store.symptomCheckerHistory;
  }

  // Clear all data for a user
  clearUserData(userId: string): void {
    localStorage.removeItem(`${this.storageKey}_${userId}`);
  }

  // Get formatted timeline for report
  getFormattedTimeline(userId: string): string {
    const history = this.getPatientHistory(userId);
    
    if (history.length === 0) {
      return 'No patient history recorded.';
    }

    const timeline = history.map((entry, index) => {
      const date = entry.timestamp.toLocaleDateString();
      const time = entry.timestamp.toLocaleTimeString();
      const source = entry.source === 'chatbot' ? 'AI Assistant' : 'Symptom Checker';
      
      let content = '';
      if (entry.data.text) {
        content = entry.data.text;
      } else if (entry.data.symptoms) {
        content = `Symptoms: ${entry.data.symptoms.join(', ')}`;
      } else if (entry.data.imageAnalysis) {
        content = `Image Analysis - Detected: ${entry.data.imageAnalysis.symptoms.join(', ')} (Confidence: ${Math.round(entry.data.imageAnalysis.confidence * 100)}%)`;
      }

      return `${index + 1}. [${date} ${time}] (${source})\n   ${content}`;
    }).join('\n\n');

    return timeline;
  }

  // Get summary for report generation
  getReportSummary(userId: string): {
    totalEntries: number;
    chatbotMessages: number;
    symptomCheckerEntries: number;
    allSymptoms: string[];
    dateRange: { start: Date | null; end: Date | null };
  } {
    const history = this.getPatientHistory(userId);
    const conversation = this.getConversationHistory(userId);
    const symptomEntries = this.getSymptomCheckerHistory(userId);

    // Extract all symptoms
    const allSymptoms: string[] = [];
    symptomEntries.forEach(entry => {
      if (entry.data.symptoms) {
        allSymptoms.push(...entry.data.symptoms);
      }
      if (entry.data.imageAnalysis) {
        allSymptoms.push(...entry.data.imageAnalysis.symptoms);
      }
    });

    // Get date range
    let start: Date | null = null;
    let end: Date | null = null;
    if (history.length > 0) {
      start = history[0].timestamp;
      end = history[history.length - 1].timestamp;
    }

    return {
      totalEntries: history.length,
      chatbotMessages: conversation.filter(msg => msg.sender === 'user').length,
      symptomCheckerEntries: symptomEntries.length,
      allSymptoms: Array.from(new Set(allSymptoms)), // Remove duplicates
      dateRange: { start, end }
    };
  }

  // Extract symptoms from conversation text
  private extractSymptomsFromText(text: string): string[] {
    const symptoms: string[] = [];
    const lowerText = text.toLowerCase();
    
    // Common symptom keywords
    const symptomKeywords = [
      'fever', 'headache', 'cough', 'pain', 'nausea', 'vomiting', 'diarrhea',
      'fatigue', 'weakness', 'dizziness', 'chest pain', 'shortness of breath',
      'sore throat', 'runny nose', 'congestion', 'rash', 'itching', 'swelling',
      'bleeding', 'numbness', 'tingling', 'anxiety', 'depression', 'insomnia'
    ];
    
    symptomKeywords.forEach(keyword => {
      if (lowerText.includes(keyword)) {
        symptoms.push(keyword.charAt(0).toUpperCase() + keyword.slice(1));
      }
    });
    
    return Array.from(new Set(symptoms)); // Remove duplicates
  }

  // Automatically generate report after chatbot interaction
  autoGenerateReport(userId: string, userName: string): AutoGeneratedReport | null {
    const history = this.getPatientHistory(userId);
    const conversation = this.getConversationHistory(userId);
    
    if (history.length === 0) {
      return null; // No data to generate report
    }

    // Extract symptoms from all sources
    const allSymptoms: string[] = [];
    
    // From symptom checker
    const symptomEntries = this.getSymptomCheckerHistory(userId);
    symptomEntries.forEach(entry => {
      if (entry.data.symptoms) {
        allSymptoms.push(...entry.data.symptoms);
      }
      if (entry.data.imageAnalysis) {
        allSymptoms.push(...entry.data.imageAnalysis.symptoms);
      }
    });
    
    // From conversation text
    conversation
      .filter(msg => msg.sender === 'user')
      .forEach(msg => {
        const extractedSymptoms = this.extractSymptomsFromText(msg.text);
        allSymptoms.push(...extractedSymptoms);
      });
    
    const uniqueSymptoms = Array.from(new Set(allSymptoms));
    
    // Get date range
    const start = history[0].timestamp;
    const end = history[history.length - 1].timestamp;
    
    // Generate conversation summary
    const recentMessages = conversation
      .filter(msg => msg.sender === 'user')
      .slice(-5) // Last 5 user messages
      .map(msg => `- ${msg.text}`)
      .join('\n');
    
    const conversationSummary = recentMessages || 'No recent conversations';
    
    // Create report
    const report: AutoGeneratedReport = {
      reportId: `AUTO-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`,
      userId,
      patientName: userName,
      generatedAt: new Date(),
      symptoms: uniqueSymptoms,
      medicalHistory: this.getFormattedTimeline(userId),
      conversationSummary,
      totalInteractions: history.length,
      dateRange: { start, end }
    };
    
    // Save report
    this.saveAutoReport(userId, report);
    
    return report;
  }

  // Save auto-generated report
  private saveAutoReport(userId: string, report: AutoGeneratedReport): void {
    const stored = localStorage.getItem(`${this.reportsKey}_${userId}`);
    let reports: AutoGeneratedReport[] = [];
    
    if (stored) {
      reports = JSON.parse(stored).map((r: any) => ({
        ...r,
        generatedAt: new Date(r.generatedAt),
        dateRange: {
          start: new Date(r.dateRange.start),
          end: new Date(r.dateRange.end)
        }
      }));
    }
    
    // Add new report at the beginning (most recent first)
    reports.unshift(report);
    
    // Keep only last 50 reports to avoid storage issues
    if (reports.length > 50) {
      reports = reports.slice(0, 50);
    }
    
    localStorage.setItem(`${this.reportsKey}_${userId}`, JSON.stringify(reports));
  }

  // Get all auto-generated reports for a user
  getAutoGeneratedReports(userId: string): AutoGeneratedReport[] {
    const stored = localStorage.getItem(`${this.reportsKey}_${userId}`);
    if (!stored) {
      return [];
    }
    
    return JSON.parse(stored).map((r: any) => ({
      ...r,
      generatedAt: new Date(r.generatedAt),
      dateRange: {
        start: new Date(r.dateRange.start),
        end: new Date(r.dateRange.end)
      }
    }));
  }

  // Get latest auto-generated report
  getLatestAutoReport(userId: string): AutoGeneratedReport | null {
    const reports = this.getAutoGeneratedReports(userId);
    return reports.length > 0 ? reports[0] : null;
  }

  // Get report by ID
  getAutoReportById(userId: string, reportId: string): AutoGeneratedReport | null {
    const reports = this.getAutoGeneratedReports(userId);
    return reports.find(r => r.reportId === reportId) || null;
  }

  // Delete auto-generated report
  deleteAutoGeneratedReport(userId: string, reportId: string): boolean {
    const stored = localStorage.getItem(`${this.reportsKey}_${userId}`);
    if (!stored) {
      return false;
    }
    
    const reports: AutoGeneratedReport[] = JSON.parse(stored).map((r: any) => ({
      ...r,
      generatedAt: new Date(r.generatedAt),
      dateRange: {
        start: new Date(r.dateRange.start),
        end: new Date(r.dateRange.end)
      }
    }));
    
    const filteredReports = reports.filter(r => r.reportId !== reportId);
    
    if (filteredReports.length === reports.length) {
      return false; // Report not found
    }
    
    localStorage.setItem(`${this.reportsKey}_${userId}`, JSON.stringify(filteredReports));
    return true;
  }
}

// Export singleton instance
export const patientDataService = new PatientDataService();
