import React, { useState, useEffect } from 'react';
import { useLanguage } from '../contexts/LanguageContext';
import { useAuth } from '../contexts/AuthContext';
import { localizeNumber } from '../utils/numberLocalization';
import { patientDataService, AutoGeneratedReport } from '../services/patientDataService';
import './DoctorReport.css';

interface ReportData {
  reportId: string;
  userId: string;
  patientName: string;
  age?: number;
  gender?: string;
  symptoms: string[];
  aiInsights: string;
  recommendedTests: string[];
  notes: string;
  createdAt: Date;
  vitalSigns?: {
    bloodPressure?: string;
    heartRate?: number;
    temperature?: number;
    oxygenLevel?: number;
  };
}

interface SavedReport extends ReportData {
  lastUpdated: Date;
  accessStatus: 'private';
}

const DoctorReport: React.FC = () => {
  const { t, currentLanguage } = useLanguage();
  const { user, isAuthenticated } = useAuth();
  const [showForm, setShowForm] = useState(false);
  const [savedReports, setSavedReports] = useState<SavedReport[]>([]);
  const [currentReport, setCurrentReport] = useState<ReportData | null>(null);
  const [showReportView, setShowReportView] = useState(false);
  const [patientHistory, setPatientHistory] = useState<string>('');
  const [reportSummary, setReportSummary] = useState<any>(null);
  const [autoGeneratedReports, setAutoGeneratedReports] = useState<AutoGeneratedReport[]>([]);
  const [viewingAutoReport, setViewingAutoReport] = useState<AutoGeneratedReport | null>(null);

  // Form state
  const [formData, setFormData] = useState({
    patientName: '',
    age: '',
    gender: '',
    symptoms: '',
    bloodPressure: '',
    heartRate: '',
    temperature: '',
    oxygenLevel: '',
    additionalNotes: ''
  });

  // Load saved reports from localStorage on mount
  useEffect(() => {
    if (isAuthenticated && user) {
      const stored = localStorage.getItem(`mediguide_reports_${user.id}`);
      if (stored) {
        const reports = JSON.parse(stored);
        setSavedReports(reports.map((r: any) => ({
          ...r,
          createdAt: new Date(r.createdAt),
          lastUpdated: new Date(r.lastUpdated)
        })));
      }
      
      // Load patient history
      const timeline = patientDataService.getFormattedTimeline(user.id);
      setPatientHistory(timeline);
      
      // Load report summary
      const summary = patientDataService.getReportSummary(user.id);
      setReportSummary(summary);
      
      // Load auto-generated reports
      const autoReports = patientDataService.getAutoGeneratedReports(user.id);
      setAutoGeneratedReports(autoReports);
    }
  }, [isAuthenticated, user]);

  // Save reports to localStorage
  const saveReportsToStorage = (reports: SavedReport[]) => {
    if (user) {
      localStorage.setItem(`mediguide_reports_${user.id}`, JSON.stringify(reports));
    }
  };

  // Generate AI insights based on symptoms and patient history
  const generateAIInsights = (symptoms: string[]): string => {
    if (symptoms.length === 0) return 'No symptoms provided for analysis.';
    
    const insights = [
      `CLINICAL OBSERVATIONS:`,
      ``,
      `Chief Complaint: Patient presents with ${symptoms.length} reported symptom${symptoms.length > 1 ? 's' : ''}.`,
      ``,
      `Symptom Analysis:`,
      ...symptoms.map((s, i) => `  ${i + 1}. ${s}`),
      ``,
      `Assessment: Based on the reported symptoms, this presentation may indicate a condition requiring`,
      `further clinical evaluation. The symptom pattern suggests the need for comprehensive physical`,
      `examination and potentially diagnostic testing to establish a definitive diagnosis.`,
      ``,
      `Clinical Recommendations:`,
      `• Complete physical examination with focus on affected systems`,
      `• Detailed patient history including onset, duration, and progression of symptoms`,
      `• Review of current medications and allergies`,
      `• Assessment of vital signs and general health status`,
      ``,
      `Note: This AI-generated analysis is intended to assist clinical decision-making and should`,
      `be interpreted in conjunction with clinical judgment and patient examination findings.`
    ];
    
    return insights.join('\n');
  };

  // Recommend tests based on symptoms
  const recommendTests = (symptoms: string[]): string[] => {
    const tests: string[] = ['Complete Blood Count (CBC)', 'Basic Metabolic Panel'];
    
    const symptomsLower = symptoms.join(' ').toLowerCase();
    
    if (symptomsLower.includes('chest') || symptomsLower.includes('heart')) {
      tests.push('ECG', 'Cardiac Enzyme Test');
    }
    if (symptomsLower.includes('fever') || symptomsLower.includes('infection')) {
      tests.push('C-Reactive Protein (CRP)', 'ESR');
    }
    if (symptomsLower.includes('sugar') || symptomsLower.includes('diabetes')) {
      tests.push('HbA1c', 'Fasting Blood Sugar');
    }
    
    return tests;
  };

  // Generate report
  const handleGenerateReport = () => {
    if (!user || !isAuthenticated) {
      alert('Please login to generate reports');
      return;
    }

    const symptoms = formData.symptoms.split(',').map(s => s.trim()).filter(s => s);
    
    // Get symptoms from patient history if form is empty
    const historicalSymptoms = reportSummary?.allSymptoms || [];
    const allSymptoms = symptoms.length > 0 ? symptoms : historicalSymptoms;
    
    if (allSymptoms.length === 0) {
      alert('Please enter symptoms or use the chatbot/symptom checker first to collect patient data');
      return;
    }

    const reportId = `RPT-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
    
    const newReport: ReportData = {
      reportId,
      userId: user.id,
      patientName: formData.patientName || user.name,
      age: formData.age ? parseInt(formData.age) : undefined,
      gender: formData.gender || undefined,
      symptoms: allSymptoms,
      aiInsights: generateAIInsights(allSymptoms),
      recommendedTests: recommendTests(allSymptoms),
      notes: formData.additionalNotes,
      createdAt: new Date(),
      vitalSigns: {
        bloodPressure: formData.bloodPressure || undefined,
        heartRate: formData.heartRate ? parseInt(formData.heartRate) : undefined,
        temperature: formData.temperature ? parseFloat(formData.temperature) : undefined,
        oxygenLevel: formData.oxygenLevel ? parseInt(formData.oxygenLevel) : undefined
      }
    };

    setCurrentReport(newReport);
    setShowReportView(true);
    
    // Save to reports list
    const savedReport: SavedReport = {
      ...newReport,
      lastUpdated: new Date(),
      accessStatus: 'private'
    };
    
    const updatedReports = [savedReport, ...savedReports];
    setSavedReports(updatedReports);
    saveReportsToStorage(updatedReports);
    
    // Reset form
    setFormData({
      patientName: '',
      age: '',
      gender: '',
      symptoms: '',
      bloodPressure: '',
      heartRate: '',
      temperature: '',
      oxygenLevel: '',
      additionalNotes: ''
    });
    setShowForm(false);
  };

  // Download report as PDF (simplified - would need proper PDF library)
  const handleDownloadReport = (report: ReportData) => {
    const reportContent = `
Mediguide – Healthcare Platform
DOCTOR-READY HEALTH REPORT
========================================

Report ID: ${report.reportId}
Date: ${report.createdAt.toLocaleString()}

PATIENT INFORMATION
-------------------
Name: ${report.patientName}
${report.age ? `Age: ${report.age} years` : ''}
${report.gender ? `Gender: ${report.gender}` : ''}

CHIEF COMPLAINTS
----------------
${report.symptoms.map((s, i) => `${i + 1}. ${s}`).join('\n')}

${patientHistory && patientHistory !== 'No patient history recorded.' ? `
PATIENT-REPORTED MEDICAL HISTORY (Chronological)
-------------------------------------------------
${patientHistory}
` : ''}

${report.vitalSigns && Object.keys(report.vitalSigns).length > 0 ? `
VITAL SIGNS
-----------
${report.vitalSigns.bloodPressure ? `Blood Pressure: ${report.vitalSigns.bloodPressure}` : ''}
${report.vitalSigns.heartRate ? `Heart Rate: ${report.vitalSigns.heartRate} bpm` : ''}
${report.vitalSigns.temperature ? `Temperature: ${report.vitalSigns.temperature}°F` : ''}
${report.vitalSigns.oxygenLevel ? `Oxygen Level: ${report.vitalSigns.oxygenLevel}%` : ''}
` : ''}

AI-GENERATED CLINICAL SUMMARY
------------------------------
${report.aiInsights}

SUGGESTED DIAGNOSTIC TESTS
---------------------------
${report.recommendedTests.map((t, i) => `${i + 1}. ${t}`).join('\n')}

${report.notes ? `
NOTES FOR CONSULTING PHYSICIAN
-------------------------------
${report.notes}
` : ''}

DISCLAIMER
----------
This report is AI-generated for clinical assistance only and does not constitute 
a medical diagnosis. The information provided should be used in conjunction with 
professional clinical judgment and patient examination. Please consult with a 
qualified healthcare professional for proper medical advice, diagnosis, and treatment.

Generated by Mediguide – Healthcare Platform
For support: smediguide@gmail.com | Emergency: 108
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Mediguide_Report_${report.reportId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Print report
  const handlePrintReport = () => {
    window.print();
  };

  // View saved report
  const handleViewReport = (report: SavedReport) => {
    setCurrentReport(report);
    setShowReportView(true);
  };

  // Delete report
  const handleDeleteReport = (reportId: string) => {
    if (window.confirm('Are you sure you want to delete this report? This action cannot be undone.')) {
      const updatedReports = savedReports.filter(r => r.reportId !== reportId);
      setSavedReports(updatedReports);
      saveReportsToStorage(updatedReports);
      
      // Close report view if the deleted report is currently being viewed
      if (currentReport && currentReport.reportId === reportId) {
        setShowReportView(false);
        setCurrentReport(null);
      }
    }
  };

  // Delete auto-generated report
  const handleDeleteAutoReport = (reportId: string) => {
    if (window.confirm('Are you sure you want to delete this auto-generated report? This action cannot be undone.')) {
      if (user) {
        patientDataService.deleteAutoGeneratedReport(user.id, reportId);
        const updatedAutoReports = autoGeneratedReports.filter(r => r.reportId !== reportId);
        setAutoGeneratedReports(updatedAutoReports);
        
        // Close report view if the deleted report is currently being viewed
        if (viewingAutoReport && viewingAutoReport.reportId === reportId) {
          setShowReportView(false);
          setViewingAutoReport(null);
        }
      }
    }
  };

  // View auto-generated report
  const handleViewAutoReport = (report: AutoGeneratedReport) => {
    setViewingAutoReport(report);
    setShowReportView(true);
  };

  // Download auto-generated report
  const handleDownloadAutoReport = (report: AutoGeneratedReport) => {
    const reportContent = `
Mediguide – Healthcare Platform
AUTOMATICALLY GENERATED DOCTOR-READY HEALTH REPORT
========================================

Report ID: ${report.reportId}
Generated: ${report.generatedAt.toLocaleString()}
Patient: ${report.patientName}

PATIENT MEDICAL HISTORY
-----------------------
Period: ${report.dateRange.start.toLocaleDateString()} to ${report.dateRange.end.toLocaleDateString()}
Total Interactions: ${report.totalInteractions}

${report.medicalHistory}

IDENTIFIED SYMPTOMS
-------------------
${report.symptoms.length > 0 ? report.symptoms.map((s, i) => `${i + 1}. ${s}`).join('\n') : 'No specific symptoms identified'}

RECENT CONVERSATION SUMMARY
---------------------------
${report.conversationSummary}

CLINICAL NOTES
--------------
This report has been automatically generated based on patient interactions with the AI health assistant.
All entries are timestamped and presented in chronological order for clinical review.

DISCLAIMER
----------
This report is AI-generated for clinical assistance only and does not constitute 
a medical diagnosis. The information provided should be used in conjunction with 
professional clinical judgment and patient examination. Please consult with a 
qualified healthcare professional for proper medical advice, diagnosis, and treatment.

Generated by Mediguide – Healthcare Platform
For support: smediguide@gmail.com | Emergency: 108
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Mediguide_AutoReport_${report.reportId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="doctor-report-page">
      <div className="report-container">
        {/* Header */}
        <div className="report-header">
          <div className="header-content">
            <div className="logo-section">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
                <path d="M9 12l2 2 4-4"/>
              </svg>
              <h1>Mediguide</h1>
            </div>
            <div className="header-actions">
              {!showForm && !showReportView && (
                <button className="btn-primary" onClick={() => setShowForm(true)}>
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <line x1="12" y1="5" x2="12" y2="19"/>
                    <line x1="5" y1="12" x2="19" y2="12"/>
                  </svg>
                  Generate New Report
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Main Content */}
        <div className="report-main">
          {!showForm && !showReportView && (
            <>
              <div className="welcome-section">
                <h2>Doctor-Ready Health Reports</h2>
                <p>Generate professional medical reports instantly with AI-assisted insights</p>
                
                {reportSummary && reportSummary.totalEntries > 0 && (
                  <div className="patient-data-summary">
                    <h3>📊 Patient Data Collected</h3>
                    <div className="summary-stats">
                      <div className="summary-stat">
                        <span className="stat-value">{reportSummary.totalEntries}</span>
                        <span className="stat-label">Total Entries</span>
                      </div>
                      <div className="summary-stat">
                        <span className="stat-value">{reportSummary.chatbotMessages}</span>
                        <span className="stat-label">Chatbot Messages</span>
                      </div>
                      <div className="summary-stat">
                        <span className="stat-value">{reportSummary.symptomCheckerEntries}</span>
                        <span className="stat-label">Symptom Checks</span>
                      </div>
                      <div className="summary-stat">
                        <span className="stat-value">{reportSummary.allSymptoms.length}</span>
                        <span className="stat-label">Unique Symptoms</span>
                      </div>
                    </div>
                    <p className="summary-note">
                      💡 Your patient data has been automatically collected. Click "Generate New Report" to create a comprehensive medical report.
                    </p>
                  </div>
                )}
              </div>

              {/* Saved Reports List */}
              <div className="saved-reports-section">
                <h3>Your Saved Reports ({savedReports.length})</h3>
                
                {savedReports.length === 0 ? (
                  <div className="empty-state">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/>
                      <polyline points="14 2 14 8 20 8"/>
                    </svg>
                    <p>No reports generated yet</p>
                    <button className="btn-secondary" onClick={() => setShowForm(true)}>
                      Create Your First Report
                    </button>
                  </div>
                ) : (
                  <div className="reports-grid">
                    {savedReports.map((report) => (
                      <div key={report.reportId} className="report-card">
                        <div className="report-card-header">
                          <div className="report-id">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/>
                              <polyline points="14 2 14 8 20 8"/>
                            </svg>
                            <span>{report.reportId}</span>
                          </div>
                          <button 
                            className="btn-delete-icon" 
                            onClick={() => handleDeleteReport(report.reportId)}
                            title="Delete Report"
                          >
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <polyline points="3 6 5 6 21 6"/>
                              <path d="M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2"/>
                              <line x1="10" y1="11" x2="10" y2="17"/>
                              <line x1="14" y1="11" x2="14" y2="17"/>
                            </svg>
                          </button>
                        </div>
                        <div className="report-card-body">
                          <h4>{report.patientName}</h4>
                          <p className="report-date">
                            {report.createdAt.toLocaleDateString()} at {report.createdAt.toLocaleTimeString()}
                          </p>
                          <div className="report-symptoms">
                            <strong>Symptoms:</strong> {report.symptoms.slice(0, 3).join(', ')}
                            {report.symptoms.length > 3 && '...'}
                          </div>
                        </div>
                        <div className="report-card-actions">
                          <button 
                            className="btn-view" 
                            onClick={() => handleViewReport(report)}
                          >
                            View
                          </button>
                          <button 
                            className="btn-download" 
                            onClick={() => handleDownloadReport(report)}
                          >
                            Download
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Auto-Generated Reports Section */}
              {autoGeneratedReports.length > 0 && (
                <div className="saved-reports-section" style={{ marginTop: '2rem' }}>
                  <h3>🤖 Auto-Generated Reports ({autoGeneratedReports.length})</h3>
                  <p style={{ color: '#666', marginBottom: '1rem', fontSize: '0.9rem' }}>
                    These reports are automatically created after each chatbot interaction, capturing your complete medical history.
                  </p>
                  
                  <div className="reports-grid">
                    {autoGeneratedReports.slice(0, 10).map((report) => (
                      <div key={report.reportId} className="report-card" style={{ borderLeft: '4px solid #0ea5e9' }}>
                        <div className="report-card-header">
                          <div className="report-id">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
                              <path d="M9 12l2 2 4-4"/>
                            </svg>
                            <span>{report.reportId}</span>
                          </div>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                            <span style={{ 
                              fontSize: '0.75rem', 
                              color: '#0ea5e9', 
                              fontWeight: '600',
                              backgroundColor: '#e0f2fe',
                              padding: '2px 8px',
                              borderRadius: '4px'
                            }}>
                              AUTO
                            </span>
                            <button 
                              className="btn-delete-icon" 
                              onClick={() => handleDeleteAutoReport(report.reportId)}
                              title="Delete Report"
                            >
                              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                <polyline points="3 6 5 6 21 6"/>
                                <path d="M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2"/>
                                <line x1="10" y1="11" x2="10" y2="17"/>
                                <line x1="14" y1="11" x2="14" y2="17"/>
                              </svg>
                            </button>
                          </div>
                        </div>
                        <div className="report-card-body">
                          <h4>{report.patientName}</h4>
                          <p className="report-date">
                            {report.generatedAt.toLocaleDateString()} at {report.generatedAt.toLocaleTimeString()}
                          </p>
                          <div className="report-symptoms">
                            <strong>Interactions:</strong> {report.totalInteractions} entries
                          </div>
                          {report.symptoms.length > 0 && (
                            <div className="report-symptoms">
                              <strong>Symptoms:</strong> {report.symptoms.slice(0, 3).join(', ')}
                              {report.symptoms.length > 3 && '...'}
                            </div>
                          )}
                        </div>
                        <div className="report-card-actions">
                          <button 
                            className="btn-view" 
                            onClick={() => handleViewAutoReport(report)}
                          >
                            View
                          </button>
                          <button 
                            className="btn-download" 
                            onClick={() => handleDownloadAutoReport(report)}
                          >
                            Download
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </>
          )}

          {/* Report Generation Form */}
          {showForm && (
            <div className="report-form-section">
              <div className="form-header">
                <h2>Generate Health Report</h2>
                <button className="btn-close" onClick={() => setShowForm(false)}>
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <line x1="18" y1="6" x2="6" y2="18"/>
                    <line x1="6" y1="6" x2="18" y2="18"/>
                  </svg>
                </button>
              </div>

              <form className="report-form" onSubmit={(e) => { e.preventDefault(); handleGenerateReport(); }}>
                <div className="form-section">
                  <h3>Patient Information</h3>
                  <div className="form-row">
                    <div className="form-group">
                      <label htmlFor="patientName">Patient Name</label>
                      <input
                        type="text"
                        id="patientName"
                        value={formData.patientName}
                        onChange={(e) => setFormData({...formData, patientName: e.target.value})}
                        placeholder="Enter patient name"
                      />
                    </div>
                    <div className="form-group">
                      <label htmlFor="age">Age</label>
                      <input
                        type="number"
                        id="age"
                        value={formData.age}
                        onChange={(e) => setFormData({...formData, age: e.target.value})}
                        placeholder="Age"
                      />
                    </div>
                    <div className="form-group">
                      <label htmlFor="gender">Gender</label>
                      <select
                        id="gender"
                        value={formData.gender}
                        onChange={(e) => setFormData({...formData, gender: e.target.value})}
                      >
                        <option value="">Select</option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                        <option value="Other">Other</option>
                      </select>
                    </div>
                  </div>
                </div>

                <div className="form-section">
                  <h3>Symptoms *</h3>
                  {reportSummary && reportSummary.allSymptoms.length > 0 && (
                    <div className="auto-fill-notice">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <circle cx="12" cy="12" r="10"/>
                        <line x1="12" y1="16" x2="12" y2="12"/>
                        <line x1="12" y1="8" x2="12.01" y2="8"/>
                      </svg>
                      <span>
                        {reportSummary.allSymptoms.length} symptom(s) detected from your history. 
                        Leave blank to use automatically, or enter new symptoms below.
                      </span>
                    </div>
                  )}
                  <div className="form-group">
                    <label htmlFor="symptoms">Enter symptoms (comma-separated) - Optional if history exists</label>
                    <textarea
                      id="symptoms"
                      value={formData.symptoms}
                      onChange={(e) => setFormData({...formData, symptoms: e.target.value})}
                      placeholder={reportSummary && reportSummary.allSymptoms.length > 0 
                        ? `Auto-detected: ${reportSummary.allSymptoms.slice(0, 3).join(', ')}${reportSummary.allSymptoms.length > 3 ? '...' : ''}`
                        : "e.g., Fever, Headache, Cough"}
                      rows={3}
                    />
                  </div>
                </div>

                <div className="form-section">
                  <h3>Vital Signs (Optional)</h3>
                  <div className="form-row">
                    <div className="form-group">
                      <label htmlFor="bloodPressure">Blood Pressure</label>
                      <input
                        type="text"
                        id="bloodPressure"
                        value={formData.bloodPressure}
                        onChange={(e) => setFormData({...formData, bloodPressure: e.target.value})}
                        placeholder="e.g., 120/80"
                      />
                    </div>
                    <div className="form-group">
                      <label htmlFor="heartRate">Heart Rate (bpm)</label>
                      <input
                        type="number"
                        id="heartRate"
                        value={formData.heartRate}
                        onChange={(e) => setFormData({...formData, heartRate: e.target.value})}
                        placeholder="e.g., 72"
                      />
                    </div>
                    <div className="form-group">
                      <label htmlFor="temperature">Temperature (°F)</label>
                      <input
                        type="number"
                        step="0.1"
                        id="temperature"
                        value={formData.temperature}
                        onChange={(e) => setFormData({...formData, temperature: e.target.value})}
                        placeholder="e.g., 98.6"
                      />
                    </div>
                    <div className="form-group">
                      <label htmlFor="oxygenLevel">Oxygen Level (%)</label>
                      <input
                        type="number"
                        id="oxygenLevel"
                        value={formData.oxygenLevel}
                        onChange={(e) => setFormData({...formData, oxygenLevel: e.target.value})}
                        placeholder="e.g., 98"
                      />
                    </div>
                  </div>
                </div>

                <div className="form-section">
                  <h3>Additional Notes</h3>
                  <div className="form-group">
                    <label htmlFor="additionalNotes">Notes for Doctor</label>
                    <textarea
                      id="additionalNotes"
                      value={formData.additionalNotes}
                      onChange={(e) => setFormData({...formData, additionalNotes: e.target.value})}
                      placeholder="Any additional information..."
                      rows={4}
                    />
                  </div>
                </div>

                <div className="form-actions">
                  <button type="button" className="btn-secondary" onClick={() => setShowForm(false)}>
                    Cancel
                  </button>
                  <button type="submit" className="btn-primary">
                    Generate Report
                  </button>
                </div>
              </form>
            </div>
          )}

          {/* Report View */}
          {showReportView && (currentReport || viewingAutoReport) && (
            <div className="report-view-section">
              <div className="report-view-header">
                <button className="btn-back" onClick={() => {
                  setShowReportView(false);
                  setViewingAutoReport(null);
                }}>
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <line x1="19" y1="12" x2="5" y2="12"/>
                    <polyline points="12 19 5 12 12 5"/>
                  </svg>
                  Back to Reports
                </button>
                <div className="report-actions">
                  <button className="btn-print" onClick={handlePrintReport}>
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <polyline points="6 9 6 2 18 2 18 9"/>
                      <path d="M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2"/>
                      <rect x="6" y="14" width="12" height="8"/>
                    </svg>
                    Print
                  </button>
                  <button className="btn-download" onClick={() => {
                    if (viewingAutoReport) {
                      handleDownloadAutoReport(viewingAutoReport);
                    } else if (currentReport) {
                      handleDownloadReport(currentReport);
                    }
                  }}>
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
                      <polyline points="7 10 12 15 17 10"/>
                      <line x1="12" y1="15" x2="12" y2="3"/>
                    </svg>
                    Download
                  </button>
                </div>
              </div>

              {viewingAutoReport ? (
                // Auto-generated report view
                <div className="report-document" id="printable-report">
                  {/* Report Header */}
                  <div className="document-header">
                    <div className="document-logo">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
                        <path d="M9 12l2 2 4-4"/>
                      </svg>
                      <div>
                        <h1>Mediguide</h1>
                        <p>Healthcare Platform</p>
                      </div>
                    </div>
                    <div className="document-meta">
                      <h2>Automatically Generated Doctor-Ready Health Report</h2>
                      <p>Report ID: <strong>{viewingAutoReport.reportId}</strong></p>
                      <p>Generated: {viewingAutoReport.generatedAt.toLocaleString()}</p>
                      <span style={{ 
                        display: 'inline-block',
                        fontSize: '0.85rem', 
                        color: '#0ea5e9', 
                        fontWeight: '600',
                        backgroundColor: '#e0f2fe',
                        padding: '4px 12px',
                        borderRadius: '6px',
                        marginTop: '8px'
                      }}>
                        🤖 AUTO-GENERATED
                      </span>
                    </div>
                  </div>

                  {/* Patient Summary */}
                  <div className="document-section">
                    <h3>Patient Information</h3>
                    <div className="info-grid">
                      <div className="info-item">
                        <span className="info-label">Name:</span>
                        <span className="info-value">{viewingAutoReport.patientName}</span>
                      </div>
                      <div className="info-item">
                        <span className="info-label">Total Interactions:</span>
                        <span className="info-value">{viewingAutoReport.totalInteractions}</span>
                      </div>
                      <div className="info-item">
                        <span className="info-label">Period:</span>
                        <span className="info-value">
                          {viewingAutoReport.dateRange.start.toLocaleDateString()} to {viewingAutoReport.dateRange.end.toLocaleDateString()}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Patient Medical History */}
                  <div className="document-section">
                    <h3>Patient Medical History (Chronological)</h3>
                    <div className="history-timeline">
                      <pre className="history-text">{viewingAutoReport.medicalHistory}</pre>
                    </div>
                  </div>

                  {/* Identified Symptoms */}
                  {viewingAutoReport.symptoms.length > 0 && (
                    <div className="document-section">
                      <h3>Identified Symptoms</h3>
                      <ul className="symptoms-list">
                        {viewingAutoReport.symptoms.map((symptom, index) => (
                          <li key={index}>{symptom}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Recent Conversation Summary */}
                  <div className="document-section">
                    <h3>Recent Conversation Summary</h3>
                    <div className="notes-box">
                      <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit' }}>
                        {viewingAutoReport.conversationSummary}
                      </pre>
                    </div>
                  </div>

                  {/* Clinical Notes */}
                  <div className="document-section">
                    <h3>Clinical Notes</h3>
                    <div className="insights-box">
                      <div className="insights-icon">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
                        </svg>
                      </div>
                      <p>
                        This report has been automatically generated based on patient interactions with the AI health assistant.
                        All entries are timestamped and presented in chronological order for clinical review. The patient has
                        engaged in {viewingAutoReport.totalInteractions} documented interaction(s) with the system.
                      </p>
                    </div>
                  </div>

                  {/* Disclaimer */}
                  <div className="document-footer">
                    <div className="disclaimer">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <circle cx="12" cy="12" r="10"/>
                        <line x1="12" y1="8" x2="12" y2="12"/>
                        <line x1="12" y1="16" x2="12.01" y2="16"/>
                      </svg>
                      <p>
                        <strong>Disclaimer:</strong> This report is AI-generated for clinical assistance only and does not constitute 
                        a medical diagnosis. Please consult with a qualified healthcare professional for proper medical advice, 
                        diagnosis, and treatment.
                      </p>
                    </div>
                    <div className="footer-info">
                      <p>Generated by Mediguide – Healthcare Platform</p>
                      <p>For support: smediguide@gmail.com | Emergency: 108</p>
                    </div>
                  </div>
                </div>
              ) : currentReport && (
                // Manual report view (existing code)
                <div className="report-document" id="printable-report">
                {/* Report Header */}
                <div className="document-header">
                  <div className="document-logo">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
                      <path d="M9 12l2 2 4-4"/>
                    </svg>
                    <div>
                      <h1>Mediguide</h1>
                      <p>Healthcare Platform</p>
                    </div>
                  </div>
                  <div className="document-meta">
                    <h2>Doctor-Ready Health Report</h2>
                    <p>Report ID: <strong>{currentReport.reportId}</strong></p>
                    <p>Date: {currentReport.createdAt.toLocaleString()}</p>
                  </div>
                </div>

                {/* Patient Summary */}
                <div className="document-section">
                  <h3>Patient Summary</h3>
                  <div className="info-grid">
                    <div className="info-item">
                      <span className="info-label">Name:</span>
                      <span className="info-value">{currentReport.patientName}</span>
                    </div>
                    {currentReport.age && (
                      <div className="info-item">
                        <span className="info-label">Age:</span>
                        <span className="info-value">{currentReport.age} years</span>
                      </div>
                    )}
                    {currentReport.gender && (
                      <div className="info-item">
                        <span className="info-label">Gender:</span>
                        <span className="info-value">{currentReport.gender}</span>
                      </div>
                    )}
                  </div>
                </div>

                {/* Symptoms Overview */}
                <div className="document-section">
                  <h3>Chief Complaints</h3>
                  <ul className="symptoms-list">
                    {currentReport.symptoms.map((symptom, index) => (
                      <li key={index}>{symptom}</li>
                    ))}
                  </ul>
                </div>

                {/* Patient-Reported History */}
                {patientHistory && patientHistory !== 'No patient history recorded.' && (
                  <div className="document-section">
                    <h3>Patient-Reported Medical History (Chronological)</h3>
                    <div className="history-timeline">
                      <pre className="history-text">{patientHistory}</pre>
                    </div>
                    {reportSummary && (
                      <div className="history-summary">
                        <p><strong>Summary:</strong> {reportSummary.totalEntries} total entries recorded from {reportSummary.chatbotMessages} chatbot interactions and {reportSummary.symptomCheckerEntries} symptom checker assessments.</p>
                        {reportSummary.dateRange.start && reportSummary.dateRange.end && (
                          <p><strong>Period:</strong> {reportSummary.dateRange.start.toLocaleDateString()} to {reportSummary.dateRange.end.toLocaleDateString()}</p>
                        )}
                      </div>
                    )}
                  </div>
                )}

                {/* Vital Signs */}
                {currentReport.vitalSigns && Object.values(currentReport.vitalSigns).some(v => v) && (
                  <div className="document-section">
                    <h3>Vital Signs</h3>
                    <div className="vitals-grid">
                      {currentReport.vitalSigns.bloodPressure && (
                        <div className="vital-card">
                          <div className="vital-icon">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <path d="M22 12h-4l-3 9L9 3l-3 9H2"/>
                            </svg>
                          </div>
                          <div className="vital-info">
                            <span className="vital-label">Blood Pressure</span>
                            <span className="vital-value">{currentReport.vitalSigns.bloodPressure}</span>
                          </div>
                        </div>
                      )}
                      {currentReport.vitalSigns.heartRate && (
                        <div className="vital-card">
                          <div className="vital-icon">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/>
                            </svg>
                          </div>
                          <div className="vital-info">
                            <span className="vital-label">Heart Rate</span>
                            <span className="vital-value">{currentReport.vitalSigns.heartRate} bpm</span>
                          </div>
                        </div>
                      )}
                      {currentReport.vitalSigns.temperature && (
                        <div className="vital-card">
                          <div className="vital-icon">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <path d="M14 14.76V3.5a2.5 2.5 0 00-5 0v11.26a4.5 4.5 0 105 0z"/>
                            </svg>
                          </div>
                          <div className="vital-info">
                            <span className="vital-label">Temperature</span>
                            <span className="vital-value">{currentReport.vitalSigns.temperature}°F</span>
                          </div>
                        </div>
                      )}
                      {currentReport.vitalSigns.oxygenLevel && (
                        <div className="vital-card">
                          <div className="vital-icon">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <circle cx="12" cy="12" r="10"/>
                              <path d="M12 6v6l4 2"/>
                            </svg>
                          </div>
                          <div className="vital-info">
                            <span className="vital-label">Oxygen Level</span>
                            <span className="vital-value">{currentReport.vitalSigns.oxygenLevel}%</span>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                )}

                {/* AI Insights */}
                <div className="document-section">
                  <h3>AI-Generated Clinical Summary</h3>
                  <div className="insights-box">
                    <div className="insights-icon">
                      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
                      </svg>
                    </div>
                    <pre className="insights-text">{currentReport.aiInsights}</pre>
                  </div>
                </div>

                {/* Recommended Tests */}
                <div className="document-section">
                  <h3>Suggested Diagnostic Tests</h3>
                  <ul className="tests-list">
                    {currentReport.recommendedTests.map((test, index) => (
                      <li key={index}>
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <polyline points="20 6 9 17 4 12"/>
                        </svg>
                        {test}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Notes */}
                {currentReport.notes && (
                  <div className="document-section">
                    <h3>Notes for Consulting Doctor</h3>
                    <div className="notes-box">
                      <p>{currentReport.notes}</p>
                    </div>
                  </div>
                )}

                {/* Disclaimer */}
                <div className="document-footer">
                  <div className="disclaimer">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <circle cx="12" cy="12" r="10"/>
                      <line x1="12" y1="8" x2="12" y2="12"/>
                      <line x1="12" y1="16" x2="12.01" y2="16"/>
                    </svg>
                    <p>
                      <strong>Disclaimer:</strong> This report is AI-generated for clinical assistance only and does not constitute 
                      a medical diagnosis. Please consult with a qualified healthcare professional for proper medical advice, 
                      diagnosis, and treatment.
                    </p>
                  </div>
                  <div className="footer-info">
                    <p>Generated by Mediguide – Healthcare Platform</p>
                    <p>For support: support@mediguide.com | Emergency: 108</p>
                  </div>
                </div>
              </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default DoctorReport;
